spring:
  application:
    name: golden-bridge
  
  datasource:
    url: jdbc:postgresql://localhost:5432/golden_bridge
    username: golden_bridge_user
    password: golden_bridge_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.goldenbridge.app: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  jwt:
    secret: ======================GoldenBridge=Spring=Boot=======================
    expiration-ms: 86400000

python:
  service:
    base-url: http://localhost:5001